# Generated by Django 5.2.9 on 2026-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0007_alter_exhibition_id_alter_exhibitionimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='registration_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
