# Generated by Django 5.2.7 on 2026-05-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0009_exhibition_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitorapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/screenshots/'),
        ),
        migrations.AlterField(
            model_name='exhibitorprofile',
            name='business_type',
            field=models.CharField(choices=[('DEVELOPER', 'Real Estate Developer'), ('BROKER', 'Real Estate Agent / Broker'), ('LOAN', 'Mortgage / Loan Provider'), ('PROPERTY_REAL_ESTATE', 'Property & Real Estate'), ('BUILDERS_CONSTRUCTION', 'Builders & Construction'), ('TRADES_CONTRACTORS', 'Trades & Contractors'), ('ARCHITECTURE_DESIGN_ENGINEERING', 'Architecture, Design & Engineering'), ('FINANCE_BANKING', 'Finance & Banking'), ('LEGAL_COMPLIANCE', 'Legal & Compliance'), ('INSPECTION_CERTIFICATION', 'Inspection & Certification'), ('PROPERTY_SERVICES', 'Property Services'), ('TECHNOLOGY_PROPTECH', 'Technology & PropTech'), ('FURNITURE_FITOUT_LIFESTYLE', 'Furniture, Fitout & Lifestyle'), ('GOVERNMENT_COMMUNITY', 'Government & Community'), ('EDUCATION_MEDIA', 'Education & Media'), ('TELECOM_INFRASTRUCTURE', 'Telecom & Infrastructure'), ('RETAIL_MISCELLANEOUS', 'Retail & Miscellaneous'), ('HOSPITALITY_CATERING', 'Hospitality & Catering'), ('HEALTH_WELLNESS', 'Health & Wellness'), ('SUSTAINABILITY_ENERGY', 'Sustainability & Energy'), ('TRANSPORT_LOGISTICS', 'Transport & Logistics'), ('RECRUITMENT_HR', 'Recruitment & HR'), ('MARKETING_ADVERTISING', 'Marketing & Advertising'), ('EVENTS_ENTERTAINMENT', 'Events & Entertainment'), ('SECURITY_SAFETY', 'Security & Safety'), ('MANUFACTURING_INDUSTRIAL', 'Manufacturing & Industrial'), ('INVESTMENT_WEALTH_MANAGEMENT', 'Investment & Wealth Management'), ('TRAINING_PROFESSIONAL_DEVELOPMENT', 'Training & Professional Development'), ('HOME_LIVING', 'Home & Living'), ('OTHER_BUSINESSES', 'Other Businesses')], max_length=60),
        ),
    ]
