# Generated by Django 5.2.7 on 2026-05-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0010_nullable_payment_screenshot_and_extended_business_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
    ]
