# Generated by Django 5.2.9 on 2026-07-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0013_eventrecap_exhibitionpricetier_recapimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exhibitions.exhibition')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
