# Generated by Django 5.2.9 on 2026-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0014_exhibitionschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitorapplication',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, upload_to='payments/screenshots/'),
        ),
    ]
