# Generated by Django 5.2.9 on 2026-08-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0015_alter_exhibitorapplication_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
