# Generated by Django 5.2.9 on 2026-08-30 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0016_exhibition_default_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='currency_code',
            field=models.CharField(default='INR', help_text='ISO 4217 currency code used for Stripe (e.g. INR, AUD, USD)', max_length=10),
        ),
        migrations.AddField(
            model_name='exhibitorapplication',
            name='selected_tier',
            field=models.ForeignKey(blank=True, help_text='Pricing tier chosen by the exhibitor at checkout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='exhibitions.exhibitionpricetier'),
        ),
        migrations.AddField(
            model_name='exhibitorapplication',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID (mobile SDK flow)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibitorapplication',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID (web flow)', max_length=255, null=True),
        ),
    ]
