# Generated by Django 5.2.9 on 2026-08-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0017_stripe_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='exhibitorapplication',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='exhibitorapplication',
            name='transaction_id',
        ),
    ]
