# Generated by Django 5.2.9 on 2026-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0018_remove_old_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorapplication',
            name='booking_ref',
            field=models.CharField(blank=True, help_text='Auto-generated booking reference e.g. NE-0076-0065', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exhibitorprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Optional exhibitor website URL', max_length=500, null=True),
        ),
    ]
